# Generated by Django 4.1.5 on 2023-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mgrn_base_uv',
        ),
        migrations.AddField(
            model_name='order',
            name='mrgn_base_uv',
            field=models.IntegerField(default=0, verbose_name='MRGN_BASE_UV'),
            preserve_default=False,
        ),
    ]
