# Generated by Django 4.1.5 on 2023-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_mrgn_base_uv'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mrgn_base_uv',
            field=models.IntegerField(default=0, verbose_name='MRGN_BASE_UV'),
            preserve_default=False,
        ),
    ]
